### ISSUE TITLE
Data processing workflow

### ISSUE THREAD

**Issue by ebuhle** [erlwagne/RhinoWork#2]
I made a `develop` branch where I'll putter around. First order of business: clean up this hacked-together data I/O and manipulation code. I think I figured out where all the raw data are. The one thing I'm not sure of: what months are in `pdo.index`?

**Comment by erlwagne** [comment]
Figures you're doing real work while I'm puttering around with labels. PDO Index months are November - March.
By the by, I think we got excited for nothing about the (Island | Year) significance (or it's lack)--when I did the loos in a big model compare, the models that include the random effect perform better; I think I just misinterpreted the output in the heat of the moment. :( I blame the White Stripes.

**Comment by ebuhle** [comment]
> PDO Index months are November - March

Thanks.

> when I did the loos in a big model compare, the models that include the random effect perform better; I think I just misinterpreted the output in the heat of the moment

I always get confused about which `elpd` is subtracted from the other in `loo::compare`, and the fact that `elpd` has the opposite sign from the familiar `deviance` makes it worse. But does the model with the random effect and covariates outperform the random effects alone?

We are going to encounter our first real GitHub task when we merge the changes I'm making in `develop` into `master`, because, although I was going to work on the data munging and you are working on the analysis, I did do a find and replace on all the "."s in our variable names. That's my one concession to the [tidyverse](https://www.tidyverse.org/) aka Hadleyverse (although I _might_ end up using `reshape2` here).

I don't know, I guess I just didn't imagine you'd be working on this on a Friday night. I'm sorry I misunderestimated you. It's definitely the White Stripes' fault.

**Comment by ebuhle** [comment]
If you'd like, I can do a pull request now so you can accept (or reject!) the minimal changes and carry on working in different sections.

**Comment by erlwagne** [comment]
Go for it!

**Comment by erlwagne** [comment]
In answer to your earlier q's, the Island + PC1 + (Island | Year) and Island + PC2 + (Island | Year) outperform Island + (Island | Year), but it's pretty negligible--something like 0.1. Still, they're the best! Which has to mean something, right? 

Okay, now to stop making trouble and go do the dishes. Looking forward to all the underscores.

**Comment by ebuhle** [comment]
OK, I made a pull request. Now you have to manually resolve the conflicts, which hopefully are minor and cosmetic.

**Comment by ebuhle** [comment]
> In answer to your earlier q's, the Island + PC1 + (Island | Year) and Island + PC2 + (Island | Year) outperform Island + (Island | Year), but it's pretty negligible

To be a fair comparison to the random-effects structure (which allows islands to behave differently through time), it should really be `Island + PC * Year`, aka `Island + PC + PC : Year`. But if both PCs are included, that adds two interaction terms instead of the (penalized) one implied by the random effects.

**Comment by erlwagne** [comment]
Ah. Adventures for tomorrow...

**Comment by ebuhle** [comment]
OK, two further Qs:

- What months are included in `cu_spring` and `cu_summer`?
- The raw SST files `PI.sst.m.csv` and `DI.sst.m.csv` contain missing values (coded very obnoxiously) that do not show up in your post-processing data (e.g., `rhau.agg.csv`). For example, in `PI.sst.m.csv`, the value for 1/1/2010 is `NA` (-32767), but in `rhau.agg.csv` the value of `sst.jan` for `PI` in 2010 is 7.14. Did you do some sort of interpolation to fill in the missing values?

**Comment by erlwagne** [comment]
1) cu spring is April - May; summer is June - Aug. but if we’re rejiggering, I’m wondering if you could make an argument that spring should be April - June, since June is mostly spring, and now I’m less concerned about treating spring as a proxy for arrival. 

2) I’m not at the computer so I can’t immediately find where I got the spring transition onset dates, but if I recall it was some NOAA site—I can forward it when I get home if you don’t find it before.
 
3) re missing sst, yes I interpolated from a slightly larger area. 

Separately, sorry for monkeying with the development branch stuff—I’ll just leave it alone and work from the master until you give me the go-ahead.

**Comment by ebuhle** [comment]
1. Actually, I was wondering why spring was a different window for CUI than for SST (Mar-May).
2. I was thinking it must be the [Bill Peterson gang](https://www.nwfsc.noaa.gov/research/divisions/fe/estuarine/oeip/dc-phys-spring-trans.cfm) at Newport, but I don't see where to download the data. (You'd think I would know this.)
3. How so? Where are the raw data used to do that?
4. Yes, my notion was that I would work on the data munging chunk in `develop` and periodically make pull requests, which would generate conflicts but be trivial to resolve as long as you're not also working on that chunk. It's not a great workflow, b/c we should really both be working in `develop` -- `master` should be "always deployable". But in this case, probably NBD. Once I get this data stuff sorted, I suggest moving to a workflow where I work on a `.RMarkdown` document that ingests chunks from the script as needed. (There is even a way to automate that by using a formal chunk naming style.)

**Comment by erlwagne** [comment]
1. Hm, alas, I'm afraid that's just a fuck-up on my part. A couple of weeks ago I was considering different periods for the spring and summer bins, and in that earlier iteration called spring Mar - May and summer Jun - Aug. But then when I thought about RHAU phenology (arrive April - May, breed / provision June - late July / early Aug), I changed the bins. But the decision came after I opted to go with the biological spring transition over coastal upwelling, and I didn't update the cu.spring or cu.summer bins to reflect that. 

2 and 3. [Here's](https://www.nwfsc.noaa.gov/research/divisions/fe/estuarine/oeip/ec-biological-spring-trans.cfm) the table I drew the spring transition data from through 2018. I then converted the dates to Julian dates and manually entered them in the rhau spreadsheet, so no downloading. Same with the SST data--on Giovanni I drew a slightly bigger box until there were sst values for the missing months (and I'm not sure why they were missing in the first place), and entered them. I can recreate that if you think it necessary, and we could use that instead--where the other values were concerned, there wasn't a material difference. 

4. Sounds good! I took a tentative look at .RMarkdown--steep learning curves indeed!

**Comment by ebuhle** [comment]
1. Okay, henceforth spring is Apr - Jun and summer is Jul - Aug.

2. Ah, so you did use the copepod-based spring transition date. Even more Bill Peterson than I thought. Well, I don't know about seabirds, but according to Brian Burke's classical-multivariate approach with Columbia R adult salmon returns, the biological transition date is a much better predictor than the physical one.

3. So you used the smaller frame except for missing values, which you filled in with values from the larger frame? Hmm. Maybe better to just use the larger frame. I couldn't manage to create a Giovanni account the other day (reCaptcha error that I couldn't get past). But if you wouldn't mind, I was actually going to suggest redoing the SST queries anyway to grab all the years available, not just the years of the RHAU study. I think it make more sense to do the PCA on the longest time series possible (MEIv2 starts in 1979).

**Comment by erlwagne** [comment]
1. Bueno.

2. Go biological or go home, I always say. I did a quick scan of the PLOS paper, and it seems like we're kind of doing a hybrid of what they did? Combining the first two PCs in a glmm along with Island. Seems very avant garde... for 2013, I guess. As for the 2015 / 2016 blob years, in the [graphs](https://www.nwfsc.noaa.gov/research/divisions/fe/estuarine/oeip/ec-biological-spring-trans.cfm), you can see they set the onset date at 365, and I see no reason to disagree with them if you also don't.  

3. New .csvs of SST data are uploaded. The MODIS data only goes back to 2002, unfortunately. In the 2012 murre paper we were looking at yesterday, they use SST data from DFO stations on Vancouver Island that I think are roughly in line longitudinally with DI and PI, respectively. I can throw them in, too, if you favor temporal reach over geographical precision. They go back to 1934.

**Comment by ebuhle** [comment]
> I did a quick scan of the PLOS paper, and it seems like we're kind of doing a hybrid of what they did?
We're doing one of the two things they did ("principal component regression"). They also did a version of the joint dimension reduction / regression procedure I was talking about yesterday at the bus stop. MCA is a classical eigenvector-based ordination method that simultaneously finds an orthogonal basis for the predictors (like PCA) and maximizes the covariance between the ordination axes and the response. I prefer likelihood-based approaches like SEM, but both are what the machine-learning people call "supervised dimension reduction".

> The MODIS data only goes back to 2002, unfortunately. In the 2012 murre paper we were looking at yesterday, they use SST data from DFO stations on Vancouver Island that I think are roughly in line longitudinally with DI and PI, respectively. I can throw them in, too, if you favor temporal reach over geographical precision. They go back to 1934.

That would be great, thanks. We can compare to the MODIS data and decide which to use (although 2002-2018 is still 2X longer than the time series we have now). You can push these files directly to `develop/data` as long as you don't overwrite any existing files.

**Comment by erlwagne** [comment]
Okay, the Canadian monthly SST csvs are up. God bless federal oceanographic agencies and their data-hoarding ways.

**Comment by ebuhle** [comment]
Given that this is a public forum, I'll bite my tongue. 

And you're in luck, b/c I've suddenly hit a roadblock in `package:salmonIPM` that I will have to refer to Scheuerell on Monday, so my data-science Marie Kondo is all yours.

**Comment by erlwagne** [comment]
Heh. I will pretend I don’t know who Marie Kondo is, but if you want to work in my awed presence rather than remotely, I’m free for a chunk of tomorrow afternoon if you want to meet up somewhere.

**Comment by ebuhle** [comment]
I won't pretend I have anything better to do with my Sunday. And I know I can walk as far as Lighthouse.

**Comment by erlwagne** [comment]
I assume you mean the coffee shop near 46th (or whatever). El and bay are headed to meet some friends at ~12:30, so 1ish?

**Comment by ebuhle** [comment]
Sure-ish! And yeah, 43rd & Phinney.

**Comment by erlwagne** [comment]
Sounds good—see you thenish!

**Comment by ebuhle** [comment]
> That  would be great, thanks. We can compare to the MODIS data and decide  which to use (although 2002-2018 is still 2X longer than the time series  we have now). You can push these files directly to develop/data as long as you don't overwrite any existing files.

Looks like you pushed them to `master`? The reason I suggested `develop` is so I wouldn't have to submit a PR in order to get them in there. I'll do that now, hopefully painlessly.

**Comment by ebuhle** [comment]
PR was able to auto-merge. New data received.

**Comment by ebuhle** [comment]
It's freakish and obnoxious that the dates in those two MODIS files are formatted completely differently (DI: `mdy_hm`; PI: `ymd_hms`). It's even worse that Excel auto-formats them identically, so you'd never suspect the actual text is different.

**Comment by ebuhle** [comment]
> As for the 2015 / 2016 blob years, in the graphs, you can see they set the onset date at 365, and I see no reason to disagree with them if you also don't.

Forgot to say, I _really_ don't like this. But given the variable type, there's not much you can do. At least it's not an outcome variable here; you'd need something like a hurdle model. And it's only a couple of years.
